### ISSUE TITLE
 Shape Mismatch in default_sam_loader_distributed with torch_em

### ISSUE THREAD

**Issue by cccoolll** [thanadol-git/ray-sam#1]
I build the docker image and writing the code for micro_sam fine tunning with Ray. Now I encountered a shape mismatch error while running the `run_sam_finetuning_hpa.py` script. The error occurs during the dataset creation process in the `default_sam_loader_distributed` function, specifically when using `torch_em.default_segmentation_dataset`. The raw images and labels have mismatched shapes, causing an `AssertionError`.

Here's the error message:
```
Traceback (most recent call last):
  File "/storage/raysam_user/run_sam_finetuning_hpa.py", line 403, in <module>
    main()
  File "/storage/raysam_user/run_sam_finetuning_hpa.py", line 376, in main
    train_loader, val_loader = get_dataloaders(
                               ^^^^^^^^^^^^^^^^
  File "/storage/raysam_user/run_sam_finetuning_hpa.py", line 167, in get_dataloaders
    train_loader = sam_training.default_sam_loader_distributed(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/raysam_user/micro_sam_ray/training/training_ray.py", line 687, in default_sam_loader_distributed
    ds = default_sam_dataset(**sam_ds_kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/raysam_user/micro_sam_ray/training/training_ray.py", line 657, in default_sam_dataset
    dataset = torch_em.default_segmentation_dataset(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/raysam_user/torch_em/segmentation.py", line 276, in default_segmentation_dataset
    ds = _load_segmentation_dataset(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/raysam_user/torch_em/segmentation.py", line 116, in _load_segmentation_dataset
    dset = SegmentationDataset(
           ^^^^^^^^^^^^^^^^^^^^
  File "/storage/raysam_user/torch_em/data/segmentation_dataset.py", line 68, in __init__
    assert shape_raw == shape_label, f"{shape_raw}, {shape_label}"
           ^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: (2048, 3), (2048, 2048)
```

**Comment by cccoolll** [comment]
Problem solved!
